#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
(cd $DIR/.. && \
case "${1:-}" in
r)
  operator-sdk run --local
  ;;
g)
  go mod tidy
  go mod verify
  operator-sdk generate crds
  operator-sdk generate k8s
  ;;
acrd)
  kubectl apply -f deploy/crds/mysql.woohhan.com_mysqls_crd.yaml
  ;;
acr)
  kubectl apply -f deploy/crds/mysql.woohhan.com_v1alpha1_mysql_cr.yaml
  ;;
ac)
  kubectl apply -f deploy/config.yaml
  ;;
dcrd)
  kubectl delete -f deploy/crds/mysql.woohhan.com_mysqls_crd.yaml
  ;;
dcr)
  kubectl delete -f deploy/crds/mysql.woohhan.com_v1alpha1_mysql_cr.yaml
  ;;
t)
  kubectl run mysql-client --image=mysql:5.7 -i --rm --restart=Never --  mysql -h mysql-read <<EOF
CREATE DATABASE test;
CREATE TABLE test.messages (message VARCHAR(250));
INSERT INTO test.messages VALUES ('hello');
EOF
  kubectl run mysql-client --image=mysql:5.7 -i -t --rm --restart=Never -- mysql -h mysql-0.mysql -e "SELECT * FROM test.messages" && \
  kubectl run mysql-client-loop --image=mysql:5.7 -i -t --rm --restart=Never -- bash -ic "while sleep 1; do mysql -h mysql-read -e 'SELECT @@server_id,NOW()'; done"
  ;;
*)
    echo " $0 [command]
Development Tools Box

Available Commands:
  r     Run local controller
  g     Generate code
  acrd  Apply CRD
  acr   Apply CR
  ac    Apply Config Map
  dcrd  Delete CRD
  dcr   Delete CR
  t     Test MySQL
" >&2
    ;;
esac
)
