apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-mysql-operator
spec:
  replicas: 3
  selector:
    matchLabels:
      name: sample-mysql-operator
  template:
    metadata:
      labels:
        name: sample-mysql-operator
    spec:
      serviceAccountName: sample-mysql-operator
      containers:
        - name: sample-mysql-operator
          # Replace this with the built image name
          image: quay.io/woohhan/sample-mysql-operator:canary
          command:
          - sample-mysql-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "sample-mysql-operator"
